import random, string, hashlib, urllib2

random = random.SystemRandom([seed])

class Challenge:
    """Class representing a challenge"""    
    def __init__(self, points, alg, desc):
        self.points = points
        self.alg = alg
        self.desc = desc
        #Default password is four digit PIN
        self.password = ''.join(random.choice(string.digits) for i in range(4)) 
        self.digest = password_to_digest(self.alg, self.password)
    
    def password_to_digest(alg, password):
        if alg in hashlib.algorithms_guarenteed:
            return getattr(hashlib, alg)()
        
    
class Mask_challenge(challenge):
    """A challenge generated by a HashCat mask built-in charsets (adds '9' for alphanumeric and removes ?b)"""
    def __init__(self, points, alg, desc, mask):
        Challenge._init__(self, points, alg, desc)
        self.mask = mask
        self.password = mask_to_random(self.mask)
        self.digest = password_to_digest(self.alg, self.password)

    def mask_to_random(mask):
        lower = string.ascii_lowercase
        upper = string.ascii_upper
        digits = string.digits
        punct = ' !"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~' #from http://hashcat.net/wiki/doku.php?id=mask_attack
    
        password = ''
        q = False #if the previous char was a ?
        for char in mask:
            if q:
                if char == 'l':
                    password.append(random.choice(lower))
                elif char == 'u':
                    password.append(random.choice(upper))
                elif char == 'd':
                    password.append(random.choice(digit))
                elif char = 's':
                    password.append(random.choice(punct))
                elif char = '9'
                    password.append(random.choice(lower + upper + digit))
                elif char = 'a'
                    password.append(random.choice(lower + upper + digit + punct))
                else:
                    raise Exception('Invalid mask')

        return password        
        
class Word_challenge(challenge):    
    """A challenge generated by concatenating words from a wordlist"""
    def __init__(self, points, alg, desc, url, max_word, num_words):
        Challenge._init__(self, points, alg, desc)
        self.url = url
        self.max_word = max_word
        self.password = url_to_random
        self.digest = password_to_digest(self.alg, self.password)
        
    def url_to_random(url, max_word, num_words):
        f = urllib2.urlopen(url)
        password = ''
        for i in range(0, num_words):
            rand_line = random.randrange(0,max_word)
            for j in range(0, rand_line - 1):
                f.readline()
            password.append(f.readline)
        

    